//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_MİMARİSİ.Models.EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_OGRT
    {
        public int OGRTID { get; set; }
        public string OGRTAD { get; set; }
        public string OGRTSOYAD { get; set; }
        public string OGRTBRANS { get; set; }
        public string OGRTMAİL { get; set; }
        public string OGRTCINSIYET { get; set; }
    }
}
